### ISSUE TITLE
s3: incorrect cache hit

### ISSUE THREAD

**Issue by shykes** [stackbrew/stackbrew#11]
In some situations, `s3.Put` will hit the task cache, causing the put task to NOT be executed. This is a silent error: the change will appear to be applied successfully, but in reality no upload has taken place.

To reproduce:

1. `s3.Put` with inputs `A`. This task will execute correctly.
2. `s3.Put` with inputs `B` different from `B`. For example, file contents may be different. This task wil also execute corectly.
3. `s3.Put` with inputs `A`. All inputs must be identical to the first run. *THIS TASK WILL BE INCORRECTLY CACHED*.

This error is not specific to S3. Any package with side-effects may be affected.

**Comment by samalba** [comment]
Fixed
